name: github-pages

on:
  push:
    branches:
      - main

env:
  BUILD_TYPE: Release

jobs:
  deploy:
    runs-on: macos-11
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - uses: actions/checkout@v2

      - name: Dependencies
        run: brew install doxygen graphviz

      - name: Doxygen
        run: |
          mkdir build && cd build
          cmake ../. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -Drnemd_configure_docs=ON
          doxygen Doxyfile

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/html
          destination_dir: html
